### ISSUE TITLE
Export timeout

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/importer-exporter#257]
I have a big 3DCityDB (v4.3.0) instance containing more than 1.5 million buildings. 
When I try to export (ImpExp v5.2.0,  both GUI and CLI via Docker) a bigger area (City of Munich) delimited by a polygon from that database using an XML query, I am facing following issue:

When I try to use the XML query listed below including `<tiling>` the export terminates after some time with this error, which probably results of a connection being closed after being idle for too long.

```
Jun 01, 2022 12:50:23 PM org.apache.tomcat.jdbc.pool.ConnectionPool terminateTransaction
WARNING: Unable to terminate transaction, connection will be closed.
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:883)
        at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:843)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.terminateTransaction(ConnectionPool.java:916)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.shouldClose(ConnectionPool.java:954)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.returnConnection(ConnectionPool.java:1018)
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:103)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:69)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
        at org.apache.tomcat.jdbc.pool.TrapException.invoke(TrapException.java:39)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
        at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:69)
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109)
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
        at jdk.proxy2/jdk.proxy2.$Proxy46.close(Unknown Source)
        at org.citydb.core.operation.exporter.database.content.DBSplitter.startQuery(DBSplitter.java:220)
        at org.citydb.core.operation.exporter.controller.Exporter.process(Exporter.java:520)
        at org.citydb.core.operation.exporter.controller.Exporter.doExport(Exporter.java:153)
        at org.citydb.cli.operation.exporter.ExportCommand.call(ExportCommand.java:114)
        at org.citydb.cli.operation.exporter.ExportCommand.call(ExportCommand.java:47)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2431)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2433)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2428)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2389)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunAll.execute(CommandLine.java:2391)
        at org.citydb.cli.ImpExpCli.process(ImpExpCli.java:305)
        at org.citydb.cli.ImpExpCli.start(ImpExpCli.java:157)
        at org.citydb.cli.ImpExpCli.main(ImpExpCli.java:149)

[12:50:23 INFO] Cleaning temporary cache.
[12:50:23 ERROR] Failed to query the database.
[12:50:23 ERROR] Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
[12:50:23 ERROR] Caused by: java.io.EOFException
[12:50:23 WARN] Database export aborted.
``` 

This is the query that times out. The export gets stuck after a couple of tiles that export just fine.
Any idea why this happens? Why do some tiles export fine and others don't?

```
select distinct b.id, b.objectclass_id, b.gmlid, b.envelope 
from citydb.building a
inner join citydb.cityobject b on a.id = b.id
inner join citydb.thematic_surface c on (a.id = c.building_id and c.objectclass_id = 35)
where b.objectclass_id = 26 and (c.lod2_multi_surface_id is not null
  and (b.envelope && $1
  and exists (
    select d.id 
	from citydb.surface_geometry d
	where d.root_id = c.lod2_multi_surface_id
	  and ST_Intersects(d.geometry, $2) = 'TRUE' ))
	  and d.geometry is not null
	  and b.envelope && $3
  ) 
```

When I use the same XML query without the `<tiling>` option, the export termiantes successfully inside 5 mins.

The full file is available here:
https://www.dropbox.com/s/f4zeb3w9pmln9y5/org.xml?dl=0

```xml
<query>
  <typeNames>
    <typeName xmlns:bldg="http://www.opengis.net/citygml/building/2.0">bldg:Building</typeName>
  </typeNames>
  <filter>
    <intersects>
      <valueReference>bldg:boundedBy/bldg:GroundSurface/bldg:lod2MultiSurface</valueReference>
      <polygon>
        <exterior dimension="2">694173.3620008957 5329252.061997809 694167.7190008956 5329252.43799781 694149.3460008951 5329250.444997812 694102.6250008941 
        ... very long list of coordinates...
        </exterior>
      </polygon>
    </intersects>
  </filter>
  <tiling>
    <extent srid="4326">
      <lowerCorner>11.33533801319881 48.06338604481738</lowerCorner>
      <upperCorner>11.74844020344211 48.25231661323132</upperCorner>
    </extent>
    <rows>10</rows>
    <columns>10</columns>
  </tiling>
</query>


```

**Comment by BWibo** [comment]
@clausnagel I did not find the time jet, but I will look into this later the week. The dataset consists of official LDBV LoD2 Buildings for southern bavaria I sady can't share. I'll let you know when I tested the build as described above.

**Comment by BWibo** [comment]
@clausnagel Hey, I finally made change and did some tests. I made the changes you proposed on top of [v5.2.0](https://github.com/3dcitydb/importer-exporter/tree/v5.2.0) and create a fresh build but still the same. The export freezes at about half of the tiles:

![grafik](https://user-images.githubusercontent.com/7643434/173773809-4eaa040a-dac4-43d3-9320-552e7087ad2a.png)
The DB session Manager shows the same as last time. One transaction in _idle in transaction_ state does not return.
![grafik](https://user-images.githubusercontent.com/7643434/173774458-33ffeedb-76d8-48b7-bcd1-15cf1a84a342.png)

I will try the same with a different server later. Possibly, this is a server side issue.

**Comment by clausnagel** [comment]
Ok, so the application freezes and you do not get an error message anymore like in your initial post?

**Comment by clausnagel** [comment]
In general, we use the Tomcat JDBC pool to manage connections and it offers many settings for testing invalid connections in the pool: https://tomcat.apache.org/tomcat-10.0-doc/jdbc-pool.html

Most of these options can be set in the Importer/Exporter config file. They are available as attributes of the `<connection>` element. Maybe you can play around and test whether a combination of settings helps to solve the issue?

This question on StackOverflow might be a good starting point: https://stackoverflow.com/questions/29620265/postgres-connection-has-been-closed-error-in-spring-boot. There are proposals for different combinations of settings. You simply need to translate the Spring Boot specific properties to the corresponding XML attributes of the Importer/Exporter config file. You can export the XSD definition of the config file via the main menu "File -> Save Settings XSD As...". The XSD contains all available XML attributes.

**Comment by BWibo** [comment]
OK, I did a lot more testing with different combinations. I edited the `impexp-config.xml` file before each run and loaded the edited file using _File_ -> _Load config_. Moreover, I reconnected the database between test runs and terminated connections from the previous run.
I also tested with ImpExp `v5.2.0` and `v5.2.0` including the edits proposed above.

The outcome is more or less the same for all tests I did. There is an _active_ connection running the query I listed above that does not return a result set. Depending on the parameters I set, this connection is assumed as dead an is being removed from the pool, leading to abortion of the export:

```xml
            <connection id="UUID_4ca99872-415d-4d2d-98c6-761a9a29fc5e" 
			loginTimeout="60" initialSize="0"
			testOnBorrow="true" 
			validationQuery="SELECT 1"
			removeAbandoned="true" 
			removeAbandonedTimeout="30"
			validationInterval="3000">
``` 

```
[11:33:21 ERROR] Failed to close the temporary cache.
[11:33:21 ERROR] Caused by: java.sql.SQLException: Connection has already been closed.
[11:33:21 ERROR] Failed to clean the temporary cache.
[11:33:21 ERROR] Caused by: java.sql.SQLException: Connection has already been closed.
[11:33:21 WARN] Database export aborted.
```

If I do not set `removeAbandoned=true` the connection with this query will not terminate. I actually had this running over night and it was still there in the morning.

```
select distinct b.id, b.objectclass_id, b.gmlid, b.envelope
from citydb.building a inner join citydb.cityobject b on a.id = b.id
inner join citydb.thematic_surface c on (a.id = c.building_id and c.objectclass_id = 35)
where b.objectclass_id = 26 and (c.lod2_multi_surface_id is not null
  and (b.envelope && $1 
  and exists (
    select d.id
    from citydb.surface_geometry d
    where d.root_id = c.lod2_multi_surface_id and d.geometry is not null
    and ST_Intersects(d.geometry, $2) = 'TRUE' )
   )
   and b.envelope && $3
 ) 
```

This leads me to the assumption, that the issue is not cause by the connection pool configuration, but rather the query. I'll take a closer look at the query now.

**Comment by BWibo** [comment]
@clausnagel I found this:
In one small part the BBox for the tiling (blue line) is slightly too small for the selection polygon:

![grafik](https://user-images.githubusercontent.com/7643434/174791575-dd56447c-1d1d-461c-a2fb-40abd5cecf87.png)

Could this potentially cause the problem?

**Comment by clausnagel** [comment]
Any news on this, @BWibo? 

Regarding the BBOX question, I am not sure whether this could cause the issue. Would be great to somehow get access to the data so that we could try and reproduce the issue. From your XML config snippet posted above, I can see that `testOnReturn="true"`. I think this would be important to test as well.

**Comment by yaozhihang** [comment]
@BWibo I think we found a workaround solution for this issue. Please enable the settings `Calculate and export bounding box for entire dataset` like this and test the export again.
![image](https://user-images.githubusercontent.com/5942971/180132770-070aeb30-bc9e-45bf-a151-f5c6c45a6ca5.png)

**Comment by BWibo** [comment]
Hey there, I can confirm this works! Thx for looking into this!

In general it would be nice, if there was an option for tiling to compute the BBox automatically, e.g. based on the extent of all features returned after all other filter criteria have been applied. If that was available, for instance, in the XML query, the user would not have to manually compute a bbox up front. The user could then just use e.g. this to perform a 10x10 tiling:

```xml

<query>
  <typeNames>
    <typeName xmlns:bldg="http://www.opengis.net/citygml/building/2.0">bldg:Building</typeName>
  </typeNames>
  <filter>
    <intersects>
      <valueReference>bldg:boundedBy/bldg:GroundSurface/bldg:lod2MultiSurface</valueReference>
      <polygon>
        <exterior dimension="2">694173.3620008957 5329252.061997809 694167.7190008956 5329252.43799781 694149.3460008951 5329250.444997812 694102.6250008941 
        ... very long list of coordinates...
        </exterior>
      </polygon>
    </intersects>
  </filter>
  <tiling>
    <rows>10</rows>
    <columns>10</columns>
  </tiling>
</query>
```

**Comment by yaozhihang** [comment]
I created a hotfix PR here. 
https://github.com/3dcitydb/importer-exporter/pull/261

**Comment by BWibo** [comment]
Thx fix seems to work, see https://github.com/3dcitydb/importer-exporter/pull/261#issuecomment-1192286126.

**Comment by BWibo** [comment]
> This feature request is related to #178 and should go into its own issue.
See #265.
