### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by mulfvik** [3dcitydb/importer-exporter#307]
I upgraded citydb to latest version and the importer/exporter to version 5.4.3. 
I get this in the cmd. Is this local for me or is it reproducible on other enviroments?

juli 18, 2024 10:54:43 FM com.formdev.flatlaf.util.LoggingFacadeImpl logSevere
SEVERE: URI has an authority component
java.lang.IllegalArgumentException: URI has an authority component
        at java.base/java.io.File.<init>(File.java:425)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.getJarFile(FlatNativeLibrary.java:251)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.findLibraryBesideJar(FlatNativeLibrary.java:196)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.createNativeLibrary(FlatNativeLibrary.java:173)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.initialize(FlatNativeLibrary.java:109)
        at com.formdev.flatlaf.ui.FlatNativeLibrary.isLoaded(FlatNativeLibrary.java:47)
        at com.formdev.flatlaf.ui.FlatNativeWindowsLibrary.isLoaded(FlatNativeWindowsLibrary.java:44)
        at com.formdev.flatlaf.util.SystemInfo.<clinit>(SystemInfo.java:131)
        at com.formdev.flatlaf.FlatLaf.initialize(FlatLaf.java:251)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:586)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
        at org.citydb.gui.GuiCommand.preprocess(GuiCommand.java:173)
        at org.citydb.cli.ImpExpCli.process(ImpExpCli.java:284)
        at org.citydb.cli.ImpExpCli.start(ImpExpCli.java:159)
        at org.citydb.cli.ImpExpCli.main(ImpExpCli.java:151)

[10:54:44 INFO] Starting 3D City Database Importer/Exporter, version 5.4.3
[10:54:44 INFO] Loading plugins
[10:54:44 INFO] Loading database schema mapping
[10:54:45 INFO] Loading ADE extensions
[10:54:45 INFO] Loading CityGML and ADE contexts
[10:54:46 INFO] Loading project settings
[10:54:46 INFO] Initializing application environment
[10:54:46 INFO] Executing 'gui' command
[10:54:46 INFO] Starting graphical user interface
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.formdev.flatlaf.ui.JavaCompatibility2 (file://XXXXX/3DCityDB-Importer-Exporter-5.4.3/lib/flatlaf-3.4.1.jar) to method sun.awt.shell.ShellFolder.get(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.formdev.flatlaf.ui.JavaCompatibility2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by clausnagel** [comment]
Hi @mulfvik, those warnings are thrown from the FlatLaf framework used for rendering the UI. It is expected behavior for Java 9 to 16. Try switching your local Java to version 17 or higher. This should make the warnings disappear. If you need to stay with your current Java version, you can simply ignore the warnings.
