### ISSUE TITLE
Connection to database could not be established

### ISSUE THREAD

**Issue by 9lovingly** [3dcitydb/importer-exporter#40]
When I installed the 3D city database importer-exporter,I run it.I click the database connect to the postGIS.However the log show:"Connection to database could not be established".Why?I input the correct infomation by the psql tools.Anyone can help me,thank you!

**Comment by clausnagel** [comment]
Go to "Preferences -> General -> Logging" and choose `DEBUG `as log level for the console. Afterwards, try and connect to the database again. The console window should then contain a stack trace of the connection error.

**Comment by 9lovingly** [comment]
Thanks @clausnagel ,I try it,and the error followed as:
Check the following stack trace for details:
java.sql.SQLException: Failed to retrieve version information from the 3D City Database instance.
	at org.citydb.database.adapter.postgis.UtilAdapter.getCityDBVersion(Unknown Source)
	at org.citydb.database.adapter.AbstractUtilAdapter.getDatabaseInfo(Unknown Source)
	at org.citydb.database.DatabaseConnectionPool.connect(Unknown Source)
	at org.citydb.database.DatabaseControllerImpl.connect(Unknown Source)
	at org.citydb.modules.database.gui.view.DatabasePanel.connect(Unknown Source)
	at org.citydb.modules.database.gui.view.DatabasePanel$6$1.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: 错误: 模式 "citydb_pkg" 不存在
  位置：15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy44.executeQuery(Unknown Source)
	... 6 more

**Comment by clausnagel** [comment]
It seems your 3DCityDB database instance is not set up correctly. At least the function `citydb_version()` in the schema `citydb_pkg` cannot be correctly executed. Have you followed the steps in the manual when setting up the 3DCityDB?

**Comment by 9lovingly** [comment]
Thanks,you are so nice.I didn't find the manual,could you give me the manual url?Thanks a lot.

**Comment by clausnagel** [comment]
Check the `Documentation` folder in the 3DCityDB repository https://github.com/3dcitydb/3dcitydb

**Comment by clausnagel** [comment]
Seems like this has been solved, so closing this issue.
