### ISSUE TITLE
Export problem with texture

### ISSUE THREAD

**Issue by nb7994** [3dcitydb/importer-exporter#55]
Hello, I'm in engineering school and I'm a beginner on the citygml format.

I try to create a 3D Visualization, I use '3DCityDB Tutorial for Beginners 3.3.0' but I'm blockin on the exercise 6 'KML Export'.

When I do my export,, i have this message : 
[11:07:49 INFO] Initializing database export...
[11:07:49 INFO] Checking for spatial indexes on geometry columns of involved tables...
[11:07:49 INFO] 1 (1x1x1) tiles will be generated.
[11:07:49 INFO] Exporting to file: C:\Users\admin\Desktop\json_files\Eglise\Tiles\0\0\Eglise_Tile_0_0_collada.kml
Exception in thread "db_exporter_pool 1" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(Unknown Source)
	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
	at javax.imageio.ImageReader.getDestination(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at org.citydb.textureAtlas.image.ImageReader.read(Unknown Source)
	at org.citydb.modules.kml.database.KmlGenericObject.fillGenericObjectForCollada(Unknown Source)
	at org.citydb.modules.kml.database.Building.readBuildingPart(Unknown Source)
	at org.citydb.modules.kml.database.Building.read(Unknown Source)
	at org.citydb.modules.kml.concurrent.KmlExportWorker.doWork(Unknown Source)
	at org.citydb.modules.kml.concurrent.KmlExportWorker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[11:09:08 INFO] Exported CityGML features:
[11:09:08 INFO] BUILDING: 1
[11:09:08 INFO] Processed geometry objects: 199951
[11:09:08 INFO] Total export time: 01 m, 18 s.
[11:09:08 INFO] Database export successfully finished.

The citygml doesn't appear in the 3D city web map.
Thanks for your help.

**Comment by FxKu** [comment]
Looks like your building object consists of many polygons and therefore textures, which seems to be too big for the export process. Try to give the Importer/Exporter more memory when launching the application, e.g. java -jar -Xmx4096m lib/3dcitydb-impexp.jar. If you still run into the same problems, maybe you can share the dataset with us for further investigation.

**Comment by clausnagel** [comment]
Closing this due to missing feedback. Feel free to re-open if you still need assistance.
