### ISSUE TITLE
No geometries exported when choosing CityObjectGroup as feature class

### ISSUE THREAD

**Issue by donatomarro** [3dcitydb/importer-exporter#6]
Hi,

I tried to export my buildings using the KML/COLLADA exporter, but choosing CityObjectGroup as feature class in addition to other feature classes always results in 0 processed geometry objects.

The documentation about the feature class filter says:

> The feature class filter in general behaves like for the CityGML import. However, 
> regarding city object groups the following rules apply: 
> 1)  If only the feature type CityObjectGroup is checked, then all city object groups 
> and all their group members (independent of their feature type) are exported.  
> 2)  If  further  feature  types  are  selected  in  addition  to  CityObjectGroup,  then  only 
> group members matching those feature types are exported. Of course, all features 
> that match the type selection but are not group members are also exported. 

So I expected that checking every feature class would result in exporting my buildings. But to successfully export the buildings I have to uncheck the CityObjectGroup feature first.

Best regards,
Donato Marro

**Comment by yaozhihang** [comment]
Hello Donato,

thank you very much for reporting this bug. I've fixed it in the Cesium-Branch. Please try it and give me your feedback.

best regards,

Zhihang

**Comment by donatomarro** [comment]
Hello Zhihang,

thank you for the quick answer! I pulled the Cesium-Branch but the export using this version results in the following two exceptions:

[22:54:20 INFO] Initializing database export...
[22:54:20 INFO] Checking for spatial indexes on geometry columns of involved tables...
[22:54:21 INFO] 12 (3x4x1) tiles will be generated.
[22:54:21 ERROR] Exception when converting bounding box geometry to DBsrs.
org.postgresql.util.PSQLException: FEHLER: parse error - invalid geometry
  Hinweis: "SRID=4326;POLYGON((Na" <-- parse error at position 21 within geometry
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
	at org.citydb.modules.common.filter.feature.BoundingBoxFilter.convertWGS84BboxToDBSrsGeometry(Unknown Source)
	at org.citydb.modules.common.filter.feature.BoundingBoxFilter.setActiveTile(Unknown Source)
	at org.citydb.modules.kml.controller.KmlExporter.doProcess(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel.doExport(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel.access$000(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel$1$1.run(Unknown Source)
[22:54:21 INFO] Exporting to file: D:\tmp\berlin\Tiles\0\0\berlin_Tile_0_0_collada.kmz
Exception in thread "Thread-9" java.lang.NullPointerException
	at org.citydb.database.adapter.postgis.GeometryConverterAdapter.getDatabaseObject(Unknown Source)
	at org.citydb.modules.kml.database.KmlSplitter.queryObjects(Unknown Source)
	at org.citydb.modules.kml.database.KmlSplitter.startQuery(Unknown Source)
	at org.citydb.modules.kml.controller.KmlExporter.doProcess(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel.doExport(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel.access$000(Unknown Source)
	at org.citydb.modules.kml.gui.view.KmlExportPanel$1$1.run(Unknown Source)
[22:54:23 INFO] User abort of database export.
[22:54:23 INFO] Waiting for objects being currently processed to end...

(I'm using exactly the same settings as I used with the exporter from the master branch)

Best regards,
Donato

**Comment by yaozhihang** [comment]
Hello Donato,

Could you share with me a snippet of your data?
My email address: zhihang.yao@tum.de

thanks and best regards,

Zhihang

**Comment by donatomarro** [comment]
Hello Zhihang,

the fix for the CityObjectGroup feature works fine now.

Thanks and best regards,
Donato

**Comment by yaozhihang** [comment]
Good, The error message posted above was caused by the wrongly entered SRID value during the creation of 3DCityDB instance.This issue can be closed now.
