### ISSUE TITLE
importer-exporter does not work

### ISSUE THREAD

**Issue by ziya61** [3dcitydb/importer-exporter#9]
I downloaded and set up 3d city database for my study. When I tried to run the importer I receive the massege ;

[14:37:39 INFO] Starting 3D City Database Importer/Exporter, version "3.2-build1"
[14:37:39 INFO] Loading plugins
[14:37:39 INFO] Initializing application environment
[14:37:42 INFO] Loading project settings
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key pref.kmlexport.lod0footprint.mode.label.footprınt
        at java.util.ResourceBundle.getObject(Unknown Source)
        at java.util.ResourceBundle.getString(Unknown Source)
        at org.citydb.config.project.kmlExporter.Lod0FootprintMode.toString(Unknown Source)
        at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(Unknown Source)
        at com.sun.java.swing.plaf.windows.WindowsComboBoxUI$WindowsComboBoxRenderer.getListCellRendererComponent(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
        at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
        at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
        at javax.swing.JList.setSelectedIndex(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup.setListSelection(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup.access$300(Unknown Source)
        at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(Unknown Source)
        at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
        at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
        at javax.swing.JComboBox.contentsChanged(Unknown Source)
        at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
        at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
        at javax.swing.DefaultComboBoxModel.addElement(Unknown Source)
        at javax.swing.JComboBox.addItem(Unknown Source)
        at org.citydb.modules.kml.gui.preferences.BuildingRenderingPanel.initGui(Unknown Source)
        at org.citydb.modules.kml.gui.preferences.BuildingRenderingPanel.<init>(Unknown Source)
        at org.citydb.modules.kml.gui.preferences.KMLExportPreferences.<init>(Unknown Source)
        at org.citydb.modules.kml.KMLExportPlugin.<init>(Unknown Source)
        at org.citydb.ImpExp.doMain(Unknown Source)
        at org.citydb.ImpExp.main(Unknown Source)

**Comment by FxKu** [comment]
Hi Ziha,
I'm using the same build and got no problems. Which OS you are using? Try to search for a project.xml in your system and send it to me. You can also try to delete it, so that the importer/exporter starts with default settings. Then it should work.

@yaozhihang maybe we should create a fallback in org.citydb.config.project.kmlExporter.Lod0FootprintMode, in case this.name() is null (for whatever reason...)

Fx

**Comment by ziya61** [comment]
Hi, sorry for late reply. I cold not find project.xml in my system

**Comment by yaozhihang** [comment]
Hi, please refer to the 3DCityDB-Documentation-3.0.0 on page 113. There you can find instructions on how to find the path of the project.xml file regarding the operating system you use

**Comment by ziya61** [comment]
I tried setuping program different computers and operating systems but receive same error:

Last login: Thu Aug 25 22:28:40 on ttys000
Ziya-MacBook-Air:~ ziya$ /Applications/3DCityDB-Importer-Exporter/3DCityDB-Importer-Exporter.command ; exit;
[22:29:42 INFO] Starting 3D City Database Importer/Exporter, version "3.2-build1"
[22:29:42 INFO] Loading plugins
[22:29:43 INFO] Initializing application environment
[22:29:49 INFO] Loading project settings
[22:29:50 INFO] Initializing plugin org.citydb.plugins.spreadsheet_gen.spsheet_gen
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key pref.kmlexport.lod0footprint.mode.label.footprınt
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.citydb.config.project.kmlExporter.Lod0FootprintMode.toString(Unknown Source)
	at com.apple.laf.AquaComboBoxRendererInternal.getListCellRendererComponent(AquaComboBoxRendererInternal.java:121)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2623)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2210)
	at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1143)
	at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:63)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:981)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1329)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:131)
	at javax.swing.JComboBox.addItem(JComboBox.java:716)
	at org.citydb.modules.kml.gui.preferences.BuildingRenderingPanel.initGui(Unknown Source)
	at org.citydb.modules.kml.gui.preferences.BuildingRenderingPanel.<init>(Unknown Source)
	at org.citydb.modules.kml.gui.preferences.KMLExportPreferences.<init>(Unknown Source)
	at org.citydb.modules.kml.KMLExportPlugin.<init>(Unknown Source)
	at org.citydb.ImpExp.doMain(Unknown Source)
	at org.citydb.ImpExp.main(Unknown Source)

I think it's not about project xml it's about java files

**Comment by clausnagel** [comment]
Seems to be an issue with locale sensitive strings (fixed in 11629189130ceeab4d44240fe6dd8e3b540d4e6a). The fix will be part of the next 3.3 release, which will be published next week. So stay tuned.

Re-open if 3.3 does not solve the bug.
